baseurl: ''
url: 'http://marlinfw.org'

version: '0.0.8-beta'
environment: development

name: 'Marlin 3D Printer Firmware'
logo: '/assets/images/logo/marlin/small.png'
description: 'Printing the planet, one layer at a time.'

repository:
  main: 'https://github.com/MarlinFirmware/Marlin'
  dev: 'https://github.com/MarlinFirmware/MarlinDev'
  doc: 'https://github.com/MarlinFirmware/MarlinDocumentation'

analytics:
  id: 'UA-76230130-1'
  domain: 'marlinfw.org'

markdown: kramdown
highlighter: rouge
timezone: 'Europe/Lisbon'

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: compressed

collections:
  basics:
    output: true
    permalink: /docs/:collection/:path:output_ext

  development:
    output: true
    title: Development
    permalink: /docs/:collection/:path:output_ext

  features:
    output: true
    title: Marlin features
    permalink: /docs/:collection/:path:output_ext

  gcode:
    output: true
    title: G-Code
    permalink: /docs/:collection/:path:output_ext

  meta:
    output: true
    permalink: /:collection/:path/

  tools:
    output: true
    permalink: /:collection/:path:output_ext

docs:
  gs: '/docs/getting-started/'

exclude:
  - '.gitignore'
  - '_config.yml'
  - 'CNAME'
  - 'Gemfile'
  - 'LICENSE'
  - 'public'
  - 'README.md'
  - 'script'
  - 'vendor'

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-bootstrap-sass

defaults:
  - # All types
    scope:
      path: '' # all files
    values:
      layout: 'default'
      author: 'MarlinFirmware'
      category: [ 'default' ]
      show:
        navbar: true
        footer: true
        breadcrumbs: false

  - # Basics collection settings
    scope:
      type: 'basics'
    values:
      layout: 'docs'
      category: [ 'Basics' ]

  - # Development collection settings
    scope:
      type: 'development'
    values:
      layout: 'docs'
      category: [ 'development' ]

  - # Features collection settings
    scope:
      type: 'features'
    values:
      layout: 'docs'
      category: [ 'features' ]

  - # G-Code collection settings
    scope:
      type: 'gcode'
    values:
      layout: 'gcode'
      category: [ 'gcode' ]

  - # Meta collection settings
    scope:
      type: 'meta'
    values:
      category: [ 'meta' ]

  - # Tools collection settings
    scope:
      type: 'gcode'
    values:
      layout: 'gcode'
      category: [ 'gcode' ]
