name: 'Marlin Firmware'
logo: '/assets/images/logo/marlin/small.png'
description: 'Printing the planet, one layer at a time.'

baseurl: ''
url: 'https://marlinfw.org'
js: '/assets/javascript/'
pull_img: '/assets/images/docs/development/pull_images/'

# Not used anymore
enforce_ssl: marlinfw.org

version: '1.0.0'
environment: development

destination: ./build

twitter:
  username: MarlinFirmware

social:
  name: Marlin Firmware
  links:
    - https://fosstodon.org/@marlinfirmware
    - https://www.facebook.com/groups/1049718498464482/
    - http://forums.reprap.org/list.php?415
    - https://discord.gg/n5NJ59y

repository:
  main: 'https://github.com/MarlinFirmware/Marlin'
  doc: 'https://github.com/MarlinFirmware/MarlinDocumentation'
  config: 'https://github.com/MarlinFirmware/Configurations'

analytics:
  id: 'UA-76230130-1'
  domain: 'marlinfw.org'

markdown: kramdown
highlighter: rouge
timezone: 'America/Chicago'

kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll_tidy:
  compress_html: true
  # exclude: ["index.html"]
  # ignore_env: development

sass:
    style: compressed

collections:
  basics:
    output: true
    permalink: /docs/:collection/:path:output_ext

  configuration:
    output: true
    title: Configuration
    permalink: /docs/:collection/:path:output_ext

  setting:
    output: true
    title: Settings
    permalink: /docs/:collection/:path:output_ext

  development:
    output: true
    title: Development
    permalink: /docs/:collection/:path:output_ext

  features:
    output: true
    title: Features
    permalink: /docs/:collection/:path:output_ext

  gcode:
    output: true
    title: G-code
    permalink: /docs/:collection/:path:output_ext

  hardware:
    output: true
    title: Hardware
    permalink: /docs/:collection/:path:output_ext

  meta:
    output: true
    permalink: /:collection/:path/

  tools:
    output: true
    permalink: /:collection/:path:output_ext

exclude:
  - '_config.yml'
  - 'Gemfile'
  - 'LICENSE'
  - 'public'
  - 'script'
  - 'vendor'

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-bootstrap-sass
  - jekyll-tidy

defaults:
  - # All types
    scope:
      path: '' # all files
    values:
      layout: 'default'
      author: 'MarlinFirmware'
      category: [ 'default' ]
      show:
        navbar: true
        footer: true
        breadcrumbs: false

  - # Basics collection settings
    scope:
      type: 'basics'
    values:
      layout: 'docs'
      category: [ 'Basics' ]

  - # Configuration collection settings
    scope:
      type: 'configuration'
    values:
      layout: 'docs'
      category: [ 'configuration' ]

  - # Settings collection settings
    scope:
      type: 'setting'
    values:
      layout: 'setting'
      category: [ 'setting' ]

  - # Development collection settings
    scope:
      type: 'development'
    values:
      layout: 'docs'
      category: [ 'development' ]

  - # Features collection settings
    scope:
      type: 'features'
    values:
      layout: 'docs'
      category: [ 'features' ]

  - # G-code collection settings
    scope:
      type: 'gcode'
    values:
      layout: 'gcode'
      category: [ 'gcode' ]

  - # Hardware collection settings
    scope:
      type: 'hardware'
    values:
      layout: 'docs'
      category: [ 'hardware' ]

  - # Meta collection settings
    scope:
      type: 'meta'
    values:
      category: [ 'meta' ]
